version: "3.9"
services:
  mysql:
    container_name: trimm_database
    platform: linux/x86_64
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PW}
    restart: always
    ports:
      - "3306:3306"
